# Generated by Django 4.1.4 on 2023-01-21 04:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_title', models.CharField(help_text='Title of announcement', max_length=100)),
                ('anno_content', models.TextField(help_text='Content of announcement')),
                ('anno_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date of creation')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Admin')], default='S', help_text='Type of user(Teacher, Student)', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user', models.ForeignKey(help_text='Teacher user', on_delete=django.db.models.deletion.CASCADE, to='school.schooluser')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_teacher', models.ForeignKey(help_text='Teacher that advises the student', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher')),
                ('student_user', models.ForeignKey(help_text='Student user', on_delete=django.db.models.deletion.CASCADE, to='school.schooluser')),
            ],
        ),
    ]
