# Generated by Django 4.1.4 on 2022-12-17 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_teacher_register_date_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='advisor_teacher',
            field=models.OneToOneField(help_text='Teacher that advises the student', on_delete=django.db.models.deletion.CASCADE, to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='register_date',
            field=models.DateTimeField(help_text='Registered date to school', verbose_name='date_registered'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(help_text='Students full name. First name first', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='register_date',
            field=models.DateTimeField(help_text='Registered date to school', verbose_name='date_registered'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(help_text='Teachers full name. First name first', max_length=100),
        ),
    ]
