# Generated by Django 4.1.4 on 2022-12-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_teacher_advising_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='advised_student',
            field=models.IntegerField(default=None),
        ),
    ]
