# Generated by Django 4.1.4 on 2023-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_advisor_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='type_user',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('A', 'Admin'), ('U', 'Undetermined')], default='S', help_text='Type of user(Teacher, Student, Admin, Undetermined)', max_length=1),
        ),
    ]
