# Generated by Django 4.1.4 on 2023-02-06 10:47

from django.db import migrations, models
import django.db.models.deletion
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_alter_schooluser_type_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Name of subject', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_time', models.IntegerField(help_text='Year + semester of the subject', validators=[school.validators.check_semester_valid])),
                ('class_subject', models.ForeignKey(help_text='Subject the class is based on', on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
    ]
