# Generated by Django 4.1.4 on 2023-02-07 17:15

from django.db import migrations, models
import django.db.models.deletion
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_subject_schoolclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_time',
            field=models.IntegerField(help_text='Year + semester of the subject', validators=[school.validators.check_schoolclass_semester_valid]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(help_text='Student user', on_delete=django.db.models.deletion.CASCADE, to='school.schooluser', validators=[school.validators.check_student_schooluser_valid]),
        ),
    ]
