# Generated by Django 4.1.4 on 2022-12-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_remove_teacher_advised_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='advised_student',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
