# Generated by Django 4.1.4 on 2023-02-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_announcement_auther_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='auther_name',
            field=models.ForeignKey(default=0, help_text='Name of auther', on_delete=django.db.models.deletion.CASCADE, to='school.schooluser'),
            preserve_default=False,
        ),
    ]
