# Generated by Django 4.1.4 on 2022-12-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='register_date',
        ),
    ]
