# Generated by Django 4.1.4 on 2023-02-08 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_schoolclass_assigned_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_relate', models.ForeignKey(help_text='Connected class to student', on_delete=django.db.models.deletion.CASCADE, to='school.schoolclass')),
                ('student_relate', models.ForeignKey(help_text='Connected student to class', on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
        ),
    ]
