# Generated by Django 4.1.4 on 2022-12-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_student_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
