# Generated by Django 4.1.4 on 2022-12-30 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0015_remove_teacher_register_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_user',
            field=models.ForeignKey(help_text='Teacher user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
