# Generated by Django 4.1.4 on 2023-02-08 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_student_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_user',
            field=models.OneToOneField(help_text='Teacher user', on_delete=django.db.models.deletion.CASCADE, to='school.schooluser'),
        ),
    ]
