# Generated by Django 4.1.4 on 2022-12-30 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0016_teacher_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(help_text='Student user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
