# Generated by Django 4.1.4 on 2023-02-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_student_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='auther_name',
            field=models.ForeignKey(help_text='Name of auther', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schooluser'),
        ),
    ]
