# Generated by Django 4.1.4 on 2023-01-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_schooluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='type_user',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher')], default='S', max_length=1),
        ),
    ]
