# Generated by Django 4.1.4 on 2023-01-20 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_schooluser_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_user',
            field=models.ForeignKey(help_text='Student user', null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schooluser'),
        ),
    ]
